name: "Meghamala Pavani"
interests:
  - Business Intelligence
  - Data Analysis
  - Predictive Analytics
email: "your-email@example.com"
phone: "+1 (123) 456-7890"
linkedin: "https://www.linkedin.com/in/yourprofile"
github: "https://github.com/yourusername"
